travis:
  secure:
    BINSTAR_TOKEN: HarvPmHD5+xryJRFH/lYvANeN8DGWeQpK90Ayx5BTbOvYmR5yEqs3nuQeevJlJxIBxOravTOxyDbXwSkN8AYUKr0FpRM8C1C34Kbea5/pffjlmcZ1PCOuXQKKgmVnDw9QWs3gVUjDXRDK2pa0dkWgSQ9wkwmqZbViWWgt6E/4SxBBSpvTlgXE846PN5NzZ45QffBeK1yYMaQ7XpcHM8oVd39DtE1LEwYV9eBim1/DI6Uv/2TbmWuIOuA2wqY6s5RhHFdOQv5ZzyK65x8yi8y2bd8CJg9D144eNrVNJnsUIqv5KxwNpE/C4gmJAGfdygkkvKVe252MkHyw/LVNNrPQdQlaxxlq/xPrLr6wm5ZGouSCv2avLowFuHGOyFAlbusgC2kp86mBnBt+h0ZpZp9nbRatIGDiS0uQOMdlENqRg0B7IAxGSIiQW12XzYcUJMCKJmEyNhiZCQs97NEJBKr0ppGvEdeQ5OW8SrS2Y26q8K8r5ZUOiHxkMY1kr9db/D+5d9EqnqBdXhf3t57Xhcuw0WXYEIj+vrna0UFy6/t2I2RqTu5JgWgoMNrq61HaKWnr2c6P0CVHYLqEBOf4qU5rbX2XmHSclvWz+QeMD+X4Z6Io5ySbIteZZ4bNR+SRzsPUK3vs7AtKgZhT3k5BE9lgsMKMbWgmIxnosHVDKddVIo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
